-- Created by: Arena.ai Agent Mode (AI) - NightCity MTA:SA resource
-- -------------------------------------------------------------------------------------------
-- client.lua - NightCity: an empty, rain-soaked futuristic megacity (no people, no vehicles, no animals).
--   * every model is allocated with engineRequestModel("object"): no vanilla model is replaced
--   * the city (models.lua / layout.lua, generated by source/build.py) is created in small batches on "nc:show"
--   * env.lua runs the environment: time of day / sun / weather / wetness / lightning -> sky.fx (sky dome), wet.fx
--     (surfaces, one shader instance per material class), water.fx (the river), post.fx (grade + sun rays)
--   * the sky dome object follows the camera; lamp / sign glow and steam are billboards (sprites.lua)
--   * procedural ambience (rain, wind, city hum, steam, neon buzz, thunder, tunnel drone), volumes follow the weather
-- City frame (layout.lua): origin = centre of the city, x east, y north, z = street level.  The server sends the world anchor
-- with nc:show (default: 900 m above the map, nothing of the vanilla world can poke through).
-- -------------------------------------------------------------------------------------------
local CFG = {
    MODEL_STEP = 8,                              -- models loaded per step
    OBJECT_STEP = 80,                            -- objects created per step
    STEP_MS = 50,
    ANCHOR = { x = 0.0, y = 0.0, z = 900.0 },    -- fallback only: the server sends the real anchor with nc:show
    SPRITE_CELL = 64,
    SOUND = true,
    DRY_IN_TUNNEL = true,
    ENV_APPLY_MS = 250,                          -- vanilla world refresh rate (the shaders are pushed every frame)
}

-- surface material classes for wet.fx (NC_SURFACES, generated by build.py, maps texture name -> group)
local GROUP_PARAMS = {
    ground   = { wet = 1.00, refl = 1.00, spec = 0.70, gloss = 26, rings = 1, emis = 0.15 },
    concrete = { wet = 0.65, refl = 0.40, spec = 0.35, gloss = 18, rings = 0, emis = 0.25 },
    metal    = { wet = 0.85, refl = 0.75, spec = 1.15, gloss = 64, rings = 0, emis = 0.10 },
    glass    = { wet = 0.55, refl = 1.35, spec = 1.50, gloss = 160, rings = 0, emis = 1.00 },
    wall     = { wet = 0.55, refl = 0.35, spec = 0.30, gloss = 22, rings = 0, emis = 1.35 },
    neon     = { wet = 0.20, refl = 0.25, spec = 0.50, gloss = 40, rings = 0, emis = 1.60 },
}

local S = {
    loaded = false, loading = false, ids = {}, txd = {}, dffs = {}, cols = {}, dome = nil, domeIdx = nil,
    shown = false, zoff = 0, anchor = nil, objs = {}, water = {}, sounds = {}, timers = {},
    rain = 0.0, hold = nil, tex = {}, grid = nil, steam = {}, drawn = 0, token = 0, waiters = {}, count = 0,
}
addEvent("nc:show", true)
addEvent("nc:hide", true)
addEvent("nc:zoff", true)

-- -------------------------------------------------------------------------------------------
-- helpers
-- -------------------------------------------------------------------------------------------
local function toWorld(px, py, pz)
    local A = S.anchor or CFG.ANCHOR
    return A.x + px, A.y + py, A.z + S.zoff + pz
end

local function toCity(wx, wy, wz)
    local A = S.anchor or CFG.ANCHOR
    return wx - A.x, wy - A.y, wz - A.z - S.zoff
end

local function track(t)
    if #S.timers > 96 then                       -- one-shot timers pile up: drop the dead ones
        local keep = {}
        for _, e in ipairs(S.timers) do if isTimer(e) then keep[#keep + 1] = e end end
        S.timers = keep
    end
    S.timers[#S.timers + 1] = t
    return t
end

local function dbg(msg) outputDebugString("[NightCity] " .. msg, 3) end
local function say(msg, r, g, b) outputChatBox("#52d8ff[NightCity] #ffffff" .. msg, r or 255, g or 255, b or 255, true) end
local function rnd(a, b) return a + (b - a) * math.random() end
local function clamp(v, a, b) if v < a then return a elseif v > b then return b end return v end

local function cityDist()
    local px, py = getElementPosition(localPlayer)
    local cx, cy = toWorld(0, 0, 0)
    return math.sqrt((px - cx) ^ 2 + (py - cy) ^ 2)
end

-- is a world position inside the covered part of the road tunnel (below street level, between the portals)?
local function inTunnel(wx, wy, wz)
    if not (S.shown and NC_TUNNEL) then return false end
    local px, py, pz = toCity(wx, wy, wz)
    local T = NC_TUNNEL
    return math.abs(px - T.x) < T.hw + 2 and py > T.cov0 and py < T.cov1 and pz < -1.0 and pz > T.zf - 3.0
end

-- -------------------------------------------------------------------------------------------
-- models
-- -------------------------------------------------------------------------------------------
local function loadOne(i)
    local def = NC_MODELS[i]
    local id = engineRequestModel("object")
    if not id then dbg("engineRequestModel failed for " .. def.name) return false end
    S.ids[i] = id
    local txd = S.txd[def.txd]
    if not txd then
        txd = engineLoadTXD("files/" .. def.txd .. ".txd")
        if not txd then dbg("cannot load TXD " .. def.txd) engineFreeModel(id) S.ids[i] = nil return false end
        S.txd[def.txd] = txd
    end
    local col = engineLoadCOL("files/" .. def.name .. ".col")
    local dff = engineLoadDFF("files/" .. def.name .. ".dff")
    if not col or not dff then
        dbg("cannot load " .. def.name)
        if col and isElement(col) then destroyElement(col) end
        if dff and isElement(dff) then destroyElement(dff) end
        engineFreeModel(id)
        S.ids[i] = nil
        return false
    end
    engineImportTXD(txd, id)
    engineReplaceCOL(col, id)
    engineReplaceModel(dff, id)
    pcall(engineSetModelLODDistance, id, def.dist or 300, true)      -- extended LOD: draw distances above 325 m
    S.cols[i], S.dffs[i] = col, dff
    return true
end

local freeModels

local function loadModels(done)
    if S.loaded then done(true) return end
    S.waiters[#S.waiters + 1] = done
    if S.loading then return end                 -- a load is already running: the callback is called when it finishes
    S.loading = true
    local i, n, failed = 0, #NC_MODELS, 0
    local function step()
        local stop = math.min(i + CFG.MODEL_STEP, n)
        while i < stop do
            i = i + 1
            if not loadOne(i) then failed = failed + 1 end
        end
        if i < n then
            setTimer(step, 50, 1)
        else
            S.loading = false
            S.loaded = failed == 0
            if failed > 0 then
                say(failed .. " of " .. n .. " models could not be loaded (see debugscript 3). The city is not created.", 255, 150, 120)
                freeModels()
            end
            local waiting = S.waiters
            S.waiters = {}
            for _, f in ipairs(waiting) do f(S.loaded) end
        end
    end
    step()
end

function freeModels()
    for _, id in pairs(S.ids) do engineFreeModel(id) end
    for _, e in pairs(S.dffs) do if isElement(e) then destroyElement(e) end end
    for _, e in pairs(S.cols) do if isElement(e) then destroyElement(e) end end
    for _, e in pairs(S.txd) do if isElement(e) then destroyElement(e) end end
    S.ids, S.dffs, S.cols, S.txd, S.loaded, S.loading = {}, {}, {}, {}, false, false
end

-- -------------------------------------------------------------------------------------------
-- objects and water
-- -------------------------------------------------------------------------------------------
local function spawnOne(o, i)
    local id = S.ids[o[1]]
    if not id then return nil end
    local x, y, z = toWorld(o[2], o[3], o[4])
    local ob = createObject(id, x, y, z, 0, 0, o[5])
    if not ob then return nil end
    setElementFrozen(ob, true)                   -- map geometry: never moved by physics
    if o[6] == "skyline" then setElementCollisionsEnabled(ob, false) end
    if i == S.domeIdx then
        -- the sky dome: no collisions, parked in another dimension until the sky shader is on (it follows the camera)
        setElementCollisionsEnabled(ob, false)
        setElementDimension(ob, 1)
        S.dome = ob
    end
    return ob
end

local function build(token, done)
    local i, n = 0, #NC_OBJECTS
    S.count = 0
    S.domeIdx = nil
    for k, m in ipairs(NC_MODELS) do
        if m.name == "nc_skydome" then
            for j, o in ipairs(NC_OBJECTS) do
                if o[1] == k then S.domeIdx = j end
            end
        end
    end
    local function step()
        if not S.shown or S.token ~= token then return end           -- hidden (or shown again) while building: stop
        local stop = math.min(i + CFG.OBJECT_STEP, n)
        while i < stop do
            i = i + 1
            S.objs[i] = spawnOne(NC_OBJECTS[i], i)
            if S.objs[i] then S.count = S.count + 1 end
        end
        if i < n then
            track(setTimer(step, CFG.STEP_MS, 1))
        else
            done()
        end
    end
    step()
end

local function even(v) return math.floor(v / 2 + 0.5) * 2 end       -- GTA water polygons need even integer coordinates

local function createRiver()
    local made = 0
    for _, w in ipairs(NC_WATER) do
        local x0, y0, z = toWorld(w[1], w[2], w[5])
        local x1, y1 = toWorld(w[3], w[4], w[5])
        x0, y0, x1, y1 = even(x0), even(y0), even(x1), even(y1)
        local e = createWater(x0, y0, z, x1, y0, z, x0, y1, z, x1, y1, z)
        if e then S.water[#S.water + 1] = { e = e, z = w[5] } made = made + 1 end
    end
    if made == 0 then dbg("createWater failed") end
    return made
end

-- -------------------------------------------------------------------------------------------
-- atmosphere: vanilla world setup + the environment engine (env.lua)
-- -------------------------------------------------------------------------------------------
local ATMO = { saved = nil, tunnel = false }

local function enforceAtmosphere()
    -- what the vanilla engine still owns: rain streaks in the tunnel, everything else follows NC_ENV
    local rain = NC_ENV.state.rainManual or (NC_ENV.state.cur and NC_ENV.state.cur.rain or 0)
    pcall(setRainLevel, ATMO.tunnel and 0 or rain)
end

local function applyAtmosphere()
    if not ATMO.saved then
        local okw, w = pcall(getWeather)
        local okt, h, m = pcall(getTime)
        ATMO.saved = { weather = okw and tonumber(w) or 0, h = okt and h or 12, m = okt and m or 0 }
    end
    pcall(setCloudsEnabled, false)               -- sky.fx draws the clouds
    pcall(setSunSize, 0)                         -- sky.fx draws the sun disc
    pcall(setBirdsEnabled, false)                -- the city is empty: no gulls, no pigeons
    pcall(setAmbientSoundEnabled, "general", false)
    pcall(setAmbientSoundEnabled, "gunfire", false)
    pcall(setOcclusionsEnabled, false)           -- vanilla occluders 900 m below must not hide anything
    pcall(setMinuteDuration, 2147483647)         -- the clock is owned by NC_ENV
    NC_ENV.tunnel = false
    NC_ENV.tick(0.0)
    NC_ENV.apply()
end

local function restoreAtmosphere()
    if not ATMO.saved then return end            -- the atmosphere was never changed: leave the world alone
    pcall(resetSkyGradient)
    pcall(resetFogDistance)
    pcall(resetFarClipDistance)
    pcall(resetHeatHaze)
    pcall(resetWindVelocity)
    pcall(resetRainLevel)
    pcall(resetSunSize)
    pcall(resetSunColor)
    pcall(resetMoonSize)
    pcall(resetWaterColor)
    pcall(setCloudsEnabled, true)
    pcall(setBirdsEnabled, true)
    pcall(setAmbientSoundEnabled, "general", true)
    pcall(setAmbientSoundEnabled, "gunfire", true)
    pcall(setOcclusionsEnabled, true)
    pcall(setMinuteDuration, 1000)
    if ATMO.saved then
        pcall(setWeather, ATMO.saved.weather)
        pcall(setTime, ATMO.saved.h, ATMO.saved.m)
    end
    ATMO.saved = nil
    ATMO.tunnel = false
    NC_ENV.tunnel = false
end

-- -------------------------------------------------------------------------------------------
-- environment frame: clock / weather / wetness / lightning + shader uniforms + the camera sky dome
-- -------------------------------------------------------------------------------------------
local FX = { surfaces = {}, sky = nil, water = nil, post = nil, src = nil, w = 0, h = 0, mode = 0, on = false, gain = 1.0, tech = {} }
local envLast, pushLast = 0, 0

-- approximate screen position of the sun for the post-process god rays (pure projection, no engine call)
local function sunScreenPos()
    local cx, cy, cz, tx, ty, tz, roll, fov = getCameraMatrix()
    local fx, fy, fz = tx - cx, ty - cy, tz - cz
    local fl = math.sqrt(fx * fx + fy * fy + fz * fz)
    if fl < 0.001 then return nil end
    fx, fy, fz = fx / fl, fy / fl, fz / fl
    local U = NC_ENV.state.sunDir
    local d = fx * U.x + fy * U.y + fz * U.z
    if d <= 0.08 then return nil end                          -- behind the camera
    local rx, ry = fy, -fx
    local rl = math.sqrt(rx * rx + ry * ry)
    if rl < 0.001 then return nil end
    rx, ry = rx / rl, ry / rl
    local ux, uy, uz = ry * fz, -rx * fz, rx * fy - ry * fx   -- up = right x forward
    local dr = U.x * rx + U.y * ry
    local du = U.x * ux + U.y * uy + U.z * uz
    local aspect = FX.w / math.max(FX.h, 1)
    local k = 1 / math.tan(math.rad(fov or 70) * 0.5)
    local sx = 0.5 + 0.5 * (dr / d) * k / aspect
    local sy = 0.5 - 0.5 * (du / d) * k
    return sx, sy
end

local function pushOne(sh, U)
    if not (sh and isElement(sh)) then return end
    dxSetShaderValue(sh, "gSunDir", U.sunX, U.sunY, U.sunZ)
    dxSetShaderValue(sh, "gSunColor", U.sunR, U.sunG, U.sunB)
    dxSetShaderValue(sh, "gSunI", U.sunI)
    dxSetShaderValue(sh, "gMoonDir", U.moonX, U.moonY, U.moonZ)
    dxSetShaderValue(sh, "gAmbient", U.ambR, U.ambG, U.ambB)
    dxSetShaderValue(sh, "gNightKeep", U.nightKeep)
    dxSetShaderValue(sh, "gNightGlow", U.nightGlow)
    dxSetShaderValue(sh, "gNight", U.night)
    dxSetShaderValue(sh, "gZenith", U.zenR, U.zenG, U.zenB)
    dxSetShaderValue(sh, "gHorizon", U.horR, U.horG, U.horB)
    dxSetShaderValue(sh, "gFogColor", U.fogR, U.fogG, U.fogB)
    dxSetShaderValue(sh, "gFogRange", U.fogNear, U.fogFar)
    dxSetShaderValue(sh, "gCloudCover", U.cover)
    dxSetShaderValue(sh, "gCloudDark", U.cloudDark)
    dxSetShaderValue(sh, "gWind", U.windX, U.windY)
    dxSetShaderValue(sh, "gQuality", U.quality)
    dxSetShaderValue(sh, "gDim", U.dim)
    dxSetShaderValue(sh, "gWet", U.wet * (ATMO.tunnel and 0.25 or 1.0))
    dxSetShaderValue(sh, "gPuddle", U.puddle * (ATMO.tunnel and 0.25 or 1.0))
    dxSetShaderValue(sh, "gExposure", U.exposure)
end

-- the fast values (time drives the rain rings, flash the lightning) are pushed every frame
local function pushFast(sh, U)
    if not (sh and isElement(sh)) then return end
    dxSetShaderValue(sh, "gTime", U.time)
    dxSetShaderValue(sh, "gFlash", U.flash)
end

local function pushUniforms(U)
    pushOne(FX.sky, U)
    pushOne(FX.water, U)
    pushOne(FX.post, U)
    if FX.water and isElement(FX.water) then
        dxSetShaderValue(FX.water, "gWaterColor", U.waterR, U.waterG, U.waterB)
    end
    if FX.post and isElement(FX.post) then
        local sx, sy = sunScreenPos()
        if sx then
            dxSetShaderValue(FX.post, "gSunScreen", sx, sy)
            local edge = math.min(math.min(sx, 1 - sx), math.min(sy, 1 - sy))
            dxSetShaderValue(FX.post, "gRayStrength", U.rayStrength * clamp(edge * 5.0, 0, 1))
        else
            dxSetShaderValue(FX.post, "gRayStrength", 0.0)
        end
        dxSetShaderValue(FX.post, "gGain", FX.gain)
    end
    for _, inst in ipairs(FX.surfaces) do
        pushOne(inst.sh, U)
        if inst.sh and isElement(inst.sh) then
            dxSetShaderValue(inst.sh, "gReflect", 1.0)
        end
    end
end

local function pushFastAll(U)
    pushFast(FX.sky, U)
    pushFast(FX.water, U)
    pushFast(FX.post, U)
    for _, inst in ipairs(FX.surfaces) do
        pushFast(inst.sh, U)
    end
end

local function envFrame(ts)
    if not S.shown then return end
    local now = getTickCount() / 1000
    local dt = clamp(now - (envLast or now), 0, 0.5)
    envLast = now
    NC_ENV.tick(dt)
    S.rain = NC_ENV.state.rainManual or (NC_ENV.state.cur and NC_ENV.state.cur.rain or 0)
    local U = NC_ENV.uniforms()
    pushFastAll(U)                                   -- every frame: rain-ring time + lightning flash
    if now - pushLast > 0.12 or NC_ENV.state.flash > 0.01 then
        pushLast = now
        pushUniforms(U)
    end
    if now - (S.envApply or 0) > CFG.ENV_APPLY_MS / 1000 then
        S.envApply = now
        NC_ENV.apply()
    end
    -- the sky dome rides on the camera
    if S.dome and isElement(S.dome) then
        local cx, cy, cz = getCameraMatrix()
        setElementPosition(S.dome, cx, cy, cz)
    end
end

local function startEnv()
    if not (S.envHandler or false) then
        addEventHandler("onClientPreRender", root, envFrame)
        S.envHandler = true
    end
    envLast = getTickCount() / 1000
    NC_ENV.apply()
    pushUniforms(NC_ENV.uniforms())
end

local function stopEnv()
    if S.envHandler then removeEventHandler("onClientPreRender", root, envFrame) end
    S.envHandler = false
end

-- -------------------------------------------------------------------------------------------
-- sprites: glow of lamps / signs, steam (billboards) - the glow follows the night glow of the timecycle
-- -------------------------------------------------------------------------------------------
local function buildSpriteGrid()
    local cell = CFG.SPRITE_CELL
    local grid = {}
    for k, s in ipairs(NC_SPRITES) do
        local key = (math.floor(s[1] / cell) + 512) * 1024 + (math.floor(s[2] / cell) + 512)
        local l = grid[key]
        if not l then l = {} grid[key] = l end
        l[#l + 1] = k
    end
    S.grid = grid
end

local function drawSprites()
    if not S.shown or not S.grid or not S.tex.glow then return end
    local cx, cy, cz = getCameraMatrix()
    local px, py, pz = toCity(cx, cy, cz)
    local cell = CFG.SPRITE_CELL
    local gx0, gy0 = math.floor(px / cell), math.floor(py / cell)
    local now = getTickCount() / 1000
    local n, maxn = 0, NC_ENV.QUALITY[NC_ENV.state.quality].sprites
    local glowK = 0.35 + 0.65 * (NC_ENV.state.key and NC_ENV.state.key.nightGlow or 1)
    for gx = gx0 - 2, gx0 + 2 do
        for gy = gy0 - 2, gy0 + 2 do
            local l = S.grid[(gx + 512) * 1024 + (gy + 512)]
            if l then
                for _, k in ipairs(l) do
                    local s = NC_SPRITES[k]
                    local dx, dy, dz = s[1] - px, s[2] - py, s[3] - pz
                    local d2 = dx * dx + dy * dy + dz * dz
                    local size = s[4]
                    local maxd = 55 + size * 22
                    if d2 < maxd * maxd and n < maxn then
                        local f = 1 - math.sqrt(d2) / maxd
                        local wx, wy, wz = toWorld(s[1], s[2], s[3])
                        if s[8] == 1 then
                            local flick = 0.92 + 0.08 * math.sin(now * 7 + k)
                            local a = clamp(f * 2.2, 0, 1) * 205 * flick * glowK
                            dxDrawMaterialLine3D(wx, wy, wz - size * 0.5, wx, wy, wz + size * 0.5, S.tex.glow, size,
                                tocolor(math.floor(s[5] * 255 + 0.5), math.floor(s[6] * 255 + 0.5), math.floor(s[7] * 255 + 0.5), math.floor(a + 0.5)), false, cx, cy, cz)
                        elseif S.tex.steam then
                            local rise = (now * 0.45 + k * 0.37) % 1.6
                            local a = clamp(f * 2.0, 0, 1) * 70 * (1 - rise / 1.6)
                            dxDrawMaterialLine3D(wx, wy, wz + rise - size * 0.5, wx, wy, wz + rise + size * 0.5, S.tex.steam, size * (0.8 + rise * 0.25),
                                tocolor(150, 140, 160, math.floor(a + 0.5)), false, cx, cy, cz)
                        end
                        n = n + 1
                    end
                end
            end
        end
    end
    S.drawn = n
end

local function startSprites()
    S.tex.glow = dxCreateTexture("files/fx/glow.png", "argb", true, "clamp")
    S.tex.steam = dxCreateTexture("files/fx/steam.png", "argb", true, "clamp")
    S.tex.noise = dxCreateTexture("files/fx/sky_noise.png", "argb", true, "clamp")   -- sky.fx cloud noise
    if not S.tex.glow then dbg("glow.png could not be loaded: no light glow") return end
    buildSpriteGrid()
    addEventHandler("onClientRender", root, drawSprites)
    S.spritesOn = true
end

local function stopSprites()
    if S.spritesOn then removeEventHandler("onClientRender", root, drawSprites) end
    S.spritesOn = false
    for k, t in pairs(S.tex) do if t and isElement(t) then destroyElement(t) end S.tex[k] = nil end
    S.grid = nil
end

-- -------------------------------------------------------------------------------------------
-- ambience
-- -------------------------------------------------------------------------------------------
local amb = {}

local function snd2(file, loop, vol)
    if not CFG.SOUND then return nil end
    local s = playSound("files/audio/" .. file .. ".wav", loop and true or false)
    if s then
        setSoundVolume(s, vol or 1)
        S.sounds[#S.sounds + 1] = s
    end
    return s
end

local function snd3(file, px, py, pz, loop, vol, minD, maxD)
    if not CFG.SOUND then return nil end
    local x, y, z = toWorld(px, py, pz)
    local s = playSound3D("files/audio/" .. file .. ".wav", x, y, z, loop and true or false)
    if s then
        setSoundVolume(s, vol or 1)
        setSoundMinDistance(s, minD or 4)
        setSoundMaxDistance(s, maxD or 40)
        S.sounds[#S.sounds + 1] = s
    end
    return s
end

local function setVol(s, v) if s and isElement(s) then setSoundVolume(s, v) end end

-- lightning from the env engine: sky flash (the dome gets gFlash) + thunder after the sound travel delay
NC_ENV.onFlash = function(strength)
    if not S.shown then return end
    pcall(setSkyGradient, 120, 130, 190, 190, 170, 235)
    track(setTimer(function() if S.shown then NC_ENV.apply() end end, 240, 1))
    track(setTimer(function() if S.shown then setVol(snd2("thunder", false, 0.55 * strength), 0.55 * strength) end end, math.random(700, 3200), 1))
end

local function startAmbience()
    amb.rain = snd2("rain_loop", true, 0)
    amb.wind = snd2("wind_loop", true, 0)
    amb.hum = snd2("hum_loop", true, 0)
    amb.drips = {}
    local T = NC_TUNNEL
    if T then
        for k = 1, 4 do
            local y = T.cov0 + (T.cov1 - T.cov0) * (k - 0.5) / 4
            local s = snd3("drip_loop", T.x + ((k % 2 == 0) and 5 or -5), y, T.zf + 2.0, true, 0.5, 3, 28)
            if s then amb.drips[#amb.drips + 1] = s end
        end
    end
    amb.near = {}
    track(setTimer(function()
        if not S.shown then return end
        local px, py, pz = getElementPosition(localPlayer)
        local inside = inTunnel(px, py, pz) and CFG.DRY_IN_TUNNEL
        local d = cityDist()
        local far = clamp((900 - d) / 300, 0, 1)
        if inside ~= ATMO.tunnel then
            ATMO.tunnel = inside
            NC_ENV.tunnel = inside
            enforceAtmosphere()                  -- no rain inside the tunnel
        end
        setVol(amb.rain, (inside and 0.04 or 0.55) * far * clamp(S.rain * 1.25, 0, 1))
        setVol(amb.wind, (inside and 0.05 or 0.28) * far * (0.5 + 0.5 * clamp(S.rain * 1.5, 0, 1)))
        setVol(amb.hum, (inside and 0.50 or 0.20) * far)
    end, 250, 0))
    -- nearby steam vents and buzzing signs: a few 3D loops that follow the player
    track(setTimer(function()
        if not S.shown then return end
        for k, e in pairs(amb.near) do
            if not isElement(e.s) then amb.near[k] = nil end
        end
        local px, py, pz = getElementPosition(localPlayer)
        local cx, cy, cz = toCity(px, py, pz)
        local want, nw = {}, 0
        for k, s in ipairs(NC_SPRITES) do
            local dx, dy = s[1] - cx, s[2] - cy
            if dx * dx + dy * dy < 900 and (s[8] == 2 or s[4] >= 2.4) and math.abs(s[3] - cz) < 40 then
                want[k] = s
                nw = nw + 1
                if nw > 40 then break end
            end
        end
        local count = 0
        for k, e in pairs(amb.near) do
            if not want[k] then
                if isElement(e.s) then destroyElement(e.s) end
                amb.near[k] = nil
            else
                count = count + 1
            end
        end
        for k, s in pairs(want) do
            if count >= 6 then break end
            if not amb.near[k] then
                local snd = snd3(s[8] == 2 and "steam_loop" or "buzz_loop", s[1], s[2], s[3], true, s[8] == 2 and 0.55 or 0.4, 3, 26)
                if snd then amb.near[k] = { s = snd } count = count + 1 end
            end
        end
    end, 1500, 0))
end

local function stopAmbience()
    for _, t in ipairs(S.timers) do if isTimer(t) then killTimer(t) end end
    S.timers = {}
    for _, s in ipairs(S.sounds) do if isElement(s) then destroyElement(s) end end
    S.sounds = {}
    amb = {}
    NC_ENV.onFlash = nil
end

-- -------------------------------------------------------------------------------------------
-- shaders: sky.fx (dome), wet.fx (surfaces, one instance per material class), water.fx, post.fx.  /ncfx 0|1|2
-- -------------------------------------------------------------------------------------------
local function makeSurface(name, group, U)
    local sh, tech = dxCreateShader("wet.fx")
    if not sh then dbg("wet.fx: " .. tostring(tech)) return nil end
    if tech == "fallback" then dbg("wet.fx: shader model 3 is not available, wet surfaces disabled") destroyElement(sh) return nil end
    local P = GROUP_PARAMS[group] or GROUP_PARAMS.concrete
    dxSetShaderValue(sh, "gMatWet", P.wet)
    dxSetShaderValue(sh, "gMatRefl", P.refl)
    dxSetShaderValue(sh, "gMatSpec", P.spec)
    dxSetShaderValue(sh, "gMatGloss", P.gloss)
    dxSetShaderValue(sh, "gMatRings", P.rings)
    dxSetShaderValue(sh, "gMatEmis", P.emis)
    dxSetShaderValue(sh, "gVColFloor", 0.20, 0.22, 0.28)
    if FX.src then dxSetShaderValue(sh, "gScreen", FX.src) end
    dxSetShaderValue(sh, "gPix", 1 / FX.w, 1 / FX.h)
    local ax, ay, az = toWorld(0, 0, 0)
    local T = NC_TUNNEL
    if T then dxSetShaderValue(sh, "gTun", ax + T.x, ay + T.cov0, ay + T.cov1, az - 1.0) end
    engineApplyShaderToWorldTexture(sh, name)
    return sh
end

local function surfacesOff()
    for _, inst in ipairs(FX.surfaces) do
        if inst.sh and isElement(inst.sh) then
            engineRemoveShaderFromWorldTexture(inst.sh, inst.name)
            destroyElement(inst.sh)
        end
    end
    FX.surfaces = {}
end

local function surfacesOn()
    if FX.surfaces[1] then return true end
    if not NC_SURFACES then return false end
    local made = 0
    for name, group in pairs(NC_SURFACES) do
        if group ~= "sky" then
            local sh = makeSurface(name, group, nil)
            if sh then
                FX.surfaces[#FX.surfaces + 1] = { sh = sh, name = name, group = group }
                made = made + 1
            end
        end
    end
    return made > 0
end

local function skyOff()
    if FX.sky and isElement(FX.sky) then destroyElement(FX.sky) end
    FX.sky = nil
    if S.dome and isElement(S.dome) then setElementDimension(S.dome, 1) end
end

local function skyOn()
    if FX.sky then return true end
    local sh, tech = dxCreateShader("sky.fx")
    if not sh then dbg("sky.fx: " .. tostring(tech)) return false end
    if tech == "fallback" then dbg("sky.fx: shader model 3 is not available, sky dome disabled") destroyElement(sh) return false end
    FX.sky = sh
    FX.tech.sky = tech
    if S.tex and S.tex.noise then dxSetShaderValue(FX.sky, "gTexture0", S.tex.noise) end   -- cloud noise
    if S.dome and isElement(S.dome) then setElementDimension(S.dome, 0) end
    return true
end

local function waterOff()
    if FX.water and isElement(FX.water) then
        engineRemoveShaderFromWorldTexture(FX.water, "waterclear256")
        destroyElement(FX.water)
    end
    FX.water = nil
end

local function waterOn()
    if FX.water then return true end
    local sh, tech = dxCreateShader("water.fx")
    if not sh then dbg("water.fx: " .. tostring(tech)) return false end
    if tech == "fallback" then dbg("water.fx: shader model 3 is not available, river water unchanged") destroyElement(sh) return false end
    engineApplyShaderToWorldTexture(sh, "waterclear256")
    FX.water = sh
    return true
end

local function postOff()
    if FX.post and isElement(FX.post) then destroyElement(FX.post) end
    FX.post = nil
end

local function postOn()
    if FX.post then return true end
    local sh, tech = dxCreateShader("post.fx")
    if not sh then dbg("post.fx: " .. tostring(tech)) return false end
    if tech == "fallback" then dbg("post.fx: no shader model 2/3, grade disabled") destroyElement(sh) return false end
    dxSetShaderValue(sh, "ScreenTexture", FX.src)
    dxSetShaderValue(sh, "gPix", 1 / FX.w, 1 / FX.h)
    dxSetShaderValue(sh, "gGain", FX.gain)
    FX.post = sh
    FX.tech.post = tech
    return true
end

local function fxFrame()
    if not FX.src or not isElement(FX.src) then return end
    dxUpdateScreenSource(FX.src, true)      -- capture NOW, before the grade pass: without 'true' the source
    if FX.post and isElement(FX.post) then  -- holds last frame's output and every frame re-grades it (rainbow runaway)
        dxDrawImage(0, 0, FX.w, FX.h, FX.post)
    end
end

local function fxStop()
    if FX.on then removeEventHandler("onClientHUDRender", root, fxFrame) end
    FX.on = false
    surfacesOff()
    skyOff()
    waterOff()
    postOff()
    if FX.src and isElement(FX.src) then destroyElement(FX.src) end
    FX.src = nil
    FX.mode = 0
end

local function fxSet(mode)
    if mode == 0 then fxStop() return 0 end
    if not FX.src then
        local sw, sh = guiGetScreenSize()
        FX.w, FX.h = sw, sh
        FX.src = dxCreateScreenSource(sw, sh)
        if not FX.src then return 0 end
    end
    local okSky = skyOn()
    local okPost = postOn()
    local okSurf = false
    local okWater = false
    if mode >= 2 then
        okSurf = surfacesOn()
        okWater = waterOn()
    else
        surfacesOff()
        waterOff()
    end
    if not (okSky or okPost or okSurf) then fxStop() return 0 end
    if not FX.on then addEventHandler("onClientHUDRender", root, fxFrame) FX.on = true end
    FX.mode = (okSurf and mode >= 2) and 2 or ((okSky or okPost) and 1 or 0)
    if S.shown then pushUniforms(NC_ENV.uniforms()) end
    return FX.mode
end

addCommandHandler("ncfx", function(_, arg)
    if not S.shown then say("the city is not shown (/ncshow).") return end
    local want = tonumber(arg)
    if want == nil then want = (FX.mode + 1) % 3 end
    want = clamp(math.floor(want), 0, 2)
    local got = fxSet(want)
    if got == want then
        say("graphics: " .. ({ [0] = "OFF (plain)", [1] = "sky + cinematic grade", [2] = "sky + grade + environment surfaces" })[got] .. "   (/ncfx 0|1|2)")
    elseif want > 0 and got == 0 then
        say("this graphics setup could not compile the shaders - running without them.", 255, 150, 120)
    else
        say("some shaders could not be compiled here, running a reduced set.", 255, 190, 120)
    end
end)

addCommandHandler("ncexposure", function(_, arg)
    local v = tonumber(arg)
    if not v then say("usage: /ncexposure <0.3 .. 4>   (now " .. string.format("%.2f", FX.gain) .. ", 1 = as designed; needs /ncfx 1 or 2)") return end
    FX.gain = clamp(v, 0.3, 4.0)
    if FX.post and isElement(FX.post) then dxSetShaderValue(FX.post, "gGain", FX.gain) end
    say("exposure " .. string.format("%.2f", FX.gain) .. (FX.post and "" or "   (the grade shader is off: /ncfx 1)"))
end)

-- -------------------------------------------------------------------------------------------
-- environment commands
-- -------------------------------------------------------------------------------------------
addCommandHandler("ncweather", function(_, arg)
    if not arg or arg == "" then
        say("usage: /ncweather <" .. table.concat(NC_ENV.WORDER, " | ") .. ">   (now " .. NC_ENV.state.weather .. ")")
        return
    end
    arg = string.lower(arg)
    if NC_ENV.setWeather(arg) then
        say("weather: " .. arg .. "   (the transition takes a few seconds)")
    else
        say("unknown weather \"" .. arg .. "\": /ncweather <" .. table.concat(NC_ENV.WORDER, " | ") .. ">")
    end
end)

addCommandHandler("ncquality", function(_, arg)
    if not arg or arg == "" then
        say("usage: /ncquality <low | medium | high | ultra>   (now " .. string.lower(NC_ENV.state.q.name) .. ")")
        return
    end
    arg = string.lower(arg)
    if NC_ENV.setQuality(arg) then
        say("quality: " .. NC_ENV.state.q.name .. "   (billboards " .. NC_ENV.state.q.sprites .. ", sun rays " .. string.format("%.2f", NC_ENV.state.q.rays) .. ")")
    else
        say("usage: /ncquality <low | medium | high | ultra>")
    end
end)

addCommandHandler("ncdaycycle", function(_, arg)
    local v = tonumber(arg)
    if not v then say("usage: /ncdaycycle <in-game hours per real minute, 0 = frozen>   (now " .. string.format("%.1f", NC_ENV.state.cycle) .. ")") return end
    NC_ENV.setCycle(v)
    say("day cycle: " .. string.format("%.1f", NC_ENV.state.cycle) .. " in-game hours per real minute")
end)

addCommandHandler("ncwet", function(_, arg)
    if not arg or arg == "" then
        say("usage: /ncwet <0 .. 1 | auto>   (now " .. (NC_ENV.state.wetManual and string.format("%.2f", NC_ENV.state.wetManual) or "auto (weather)") .. ")")
        return
    end
    if arg == "auto" then
        NC_ENV.setWet(nil)
        say("wetness: driven by the weather again")
    else
        local v = tonumber(arg)
        if not v then say("usage: /ncwet <0 .. 1 | auto>") return end
        NC_ENV.setWet(clamp(v, 0, 1))
        say("wetness held at " .. string.format("%.2f", NC_ENV.state.wetManual))
    end
end)

addCommandHandler("ncenv", function()
    say(NC_ENV.status())
end)

addCommandHandler("ncflash", function()
    if not S.shown then say("the city is not shown (/ncshow).") return end
    NC_ENV.fireFlash()
    say("lightning fired (only visible while the sky / surface shaders run).")
end)

-- -------------------------------------------------------------------------------------------
-- show / hide
-- -------------------------------------------------------------------------------------------
local clearCity

local function waitGround(token, x, y, z, tries, done)
    if not S.shown or S.token ~= token then return end
    local hit = processLineOfSight(x, y, z + 4.0, x, y, z - 8.0, true, false, false, true, false)
    if hit then done(true) return end
    if tries <= 0 then done(false) return end
    track(setTimer(function() waitGround(token, x, y, z, tries - 1, done) end, 300, 1))
end

-- teleport inside the city: the player is held until the collision around the destination is streamed in (the sky city is 900 m up)
local function safeTeleport(x, y, z)
    setElementPosition(localPlayer, x, y, z)
    setElementVelocity(localPlayer, 0, 0, 0)
    S.hold = true
    S.tp = (S.tp or 0) + 1
    local mine = S.tp
    setElementFrozen(localPlayer, true)
    waitGround(S.token, x, y, z, 40, function(found)
        if S.tp ~= mine then return end                                  -- a newer teleport took over
        if found then
            setElementFrozen(localPlayer, false)
            S.hold = nil
        else
            say("the ground collision is not available here yet - you stay frozen. /ncview again or /nchide.", 255, 150, 120)
        end
    end)
end

local function showCity(zoff, ax, ay, az)
    if S.shown then clearCity() end
    S.token = S.token + 1
    local token = S.token
    if ax and ay and az then S.anchor = { x = ax, y = ay, z = az } end
    S.zoff = (zoff or 0) + (S.zBias or 0)                          -- /setz trim survives hide / show
    local near = cityDist() < 600
    if near then setElementFrozen(localPlayer, true) S.hold = true end        -- hold the player in the air until the ground exists
    if not S.loaded then say("loading " .. #NC_MODELS .. " models and " .. #NC_OBJECTS .. " objects - this takes a few seconds ...") end
    loadModels(function(ok)
        if S.token ~= token then return end                                    -- hidden or shown again while the models were loading
        if not ok then
            if near then setElementFrozen(localPlayer, false) S.hold = nil end
            return
        end
        S.shown = true
        applyAtmosphere()
        startEnv()
        build(token, function()
            createRiver()
            startSprites()
            startAmbience()
            fxSet(2)
            local P = NC_POINTS.spawn
            local x, y, z = toWorld(P[1], P[2], P[3])
            if near then
                waitGround(token, x, y, z, 40, function(ok2)
                    if ok2 then
                        setElementFrozen(localPlayer, false)
                        S.hold = nil
                    else
                        say("the ground collision is not available yet - you stay frozen. /nchide returns you to the map.", 255, 150, 120)
                    end
                end)
            end
            say(S.count .. " objects.  /nchide removes it, /nctour camera tour, /ncfree free camera, /ncview <point> teleport,")
            say("/ncfx graphics, /ncquality <low-ultra>, /ncweather <preset>, /nctime <hour>, /ncdaycycle <h/min>, /ncwet <0-1|auto>, /ncexposure <0.3-4>, /ncrain <0-1>, /ncenv, /ncinfo")
        end)
    end)
end

function clearCity()
    S.token = S.token + 1                        -- cancels a show that is still loading / building
    stopEnv()
    for _, e in pairs(S.objs) do if e and isElement(e) then destroyElement(e) end end
    for _, w in pairs(S.water) do if w and isElement(w.e) then destroyElement(w.e) end end
    S.objs, S.water, S.dome, S.domeIdx = {}, {}, nil, nil
    fxStop()
    stopSprites()
    stopAmbience()
    restoreAtmosphere()
    if S.hold then setElementFrozen(localPlayer, false) S.hold = nil end
    S.shown = false
    if NC and NC.onHide then NC.onHide() end
end

addEventHandler("nc:show", resourceRoot, function(zoff, ax, ay, az) showCity(zoff, ax, ay, az) end)
addEventHandler("nc:hide", resourceRoot, function()
    local was = S.shown
    clearCity()
    if was then say("NightCity removed.") end
end)

-- /nczoff trims the height of the whole city
-- city deck height: the city ground sits at (S.anchor or CFG.ANCHOR).z + S.zoff; /setz sets it, /ncz trims it
local function cityZ()
    return (S.anchor or CFG.ANCHOR).z + S.zoff
end

local function shiftCity(dz)
    S.zoff = S.zoff + dz
    if not S.shown then return end
    for k, e in pairs(S.objs) do
        if e and isElement(e) then
            local o = NC_OBJECTS[k]
            if k ~= S.domeIdx then
                local x, y, z = toWorld(o[2], o[3], o[4])
                setElementPosition(e, x, y, z)
            end
        end
    end
    for _, w in pairs(S.water) do
        if w and isElement(w.e) then pcall(setWaterLevel, w.e, (S.anchor or CFG.ANCHOR).z + S.zoff + w.z) end
    end
end

addEventHandler("nc:zoff", resourceRoot, function(dz) shiftCity(dz) end)

addCommandHandler("setz", function(_, arg)
    local v = tonumber(arg)
    if not v then
        say("usage: /setz <height | +d | -d>   (city deck height above the map, now " .. string.format("%.0f", cityZ()) .. ")")
        return
    end
    local dz
    if arg:sub(1, 1) == "+" or arg:sub(1, 1) == "-" then
        dz = v                                                     -- relative: +100 lifts, -100 drops
    else
        dz = v - cityZ()                                           -- absolute world Z of the city deck
    end
    S.zBias = (S.zBias or 0) + dz                                  -- keeps the trim across /nchide //ncshow
    shiftCity(dz)
    if S.shown then
        say("city height " .. string.format("%.0f", cityZ()))
    else
        say("city height " .. string.format("%.0f", cityZ()) .. " (applies at the next /ncshow)")
    end
end)

-- safety net for the sky city: anyone who somehow steps off the edge is brought back to the spawn point
setTimer(function()
    if not S.shown or S.hold or not S.anchor or S.anchor.z < 300 then return end
    local px, py, pz = getElementPosition(localPlayer)
    local cx, cy, cz = toWorld(0, 0, 0)
    local dx, dy = math.abs(px - cx), math.abs(py - cy)
    local E = NC_EXTENT
    local outside = dx > (E.x1 - E.x0) / 2 + 40 or dy > (E.y1 - E.y0) / 2 + 40
    if (pz < cz - 40 and dx < 900 and dy < 900) or (outside and dx < 1100 and dy < 1100 and pz < cz + 30) then
        local P = NC_POINTS.spawn
        local x, y, z = toWorld(P[1], P[2], P[3] + 1.0)
        safeTeleport(x, y, z)
    end
end, 1000, 0)

-- -------------------------------------------------------------------------------------------
-- small commands
-- -------------------------------------------------------------------------------------------
addCommandHandler("ncrain", function(_, arg)
    if arg == "auto" then
        NC_ENV.setRain(nil)
        if S.shown then enforceAtmosphere() say("rain: driven by the weather again") end
        return
    end
    local v = tonumber(arg)
    if not v then say("usage: /ncrain <0 .. 1 | auto>   (now " .. (NC_ENV.state.rainManual and string.format("%.2f", NC_ENV.state.rainManual) or "auto (weather)") .. ")") return end
    NC_ENV.setRain(clamp(v, 0, 1))
    if S.shown then
        enforceAtmosphere()
        say("rain " .. string.format("%.2f", NC_ENV.state.rainManual))
    end
end)

addCommandHandler("nctime", function(_, arg, minute)
    local h = tonumber(arg)
    if not h then say("usage: /nctime <hour 0-23> [minute]   (or /ncdaycycle <h/min> to let time run)") return end
    NC_ENV.setClock(h, tonumber(minute))
    if S.shown then NC_ENV.apply() say(string.format("clock %02d:%02d", math.floor(NC_ENV.state.hour), math.floor((NC_ENV.state.hour % 1) * 60))) end
end)

addCommandHandler("ncview", function(_, name)
    if not S.shown then say("the city is not shown (/ncshow).") return end
    local P = name and NC_POINTS[name]
    if not P then
        local names = {}
        for k in pairs(NC_POINTS) do names[#names + 1] = k end
        table.sort(names)
        say("usage: /ncview <" .. table.concat(names, " | ") .. ">")
        return
    end
    local x, y, z = toWorld(P[1], P[2], P[3] + 0.5)
    safeTeleport(x, y, z)
end)

addCommandHandler("ncinfo", function()
    local nobj = 0
    for _, e in pairs(S.objs) do if e and isElement(e) then nobj = nobj + 1 end end
    local px, py, pz = getElementPosition(localPlayer)
    local cx, cy, cz = toCity(px, py, pz)
    say(string.format("shown=%s  models=%d  objects=%d  water=%d  glow sprites drawn=%d  graphics=%d  shaders=%d  tunnel=%s  you: x %.0f y %.0f z %.1f (city frame)",
        tostring(S.shown), #NC_MODELS, nobj, #S.water, S.drawn, FX.mode, #FX.surfaces + (FX.sky and 1 or 0) + (FX.water and 1 or 0) + (FX.post and 1 or 0),
        tostring(inTunnel(px, py, pz)), cx, cy, cz))
    say(NC_ENV.status())
end)

-- -------------------------------------------------------------------------------------------
-- shared with tour.lua and env.lua
-- -------------------------------------------------------------------------------------------
NC = { toWorld = toWorld, toCity = toCity, say = say, track = track, clamp = clamp, isShown = function() return S.shown end,
       hold = function() return S.hold end, onHide = nil, env = NC_ENV }

addEventHandler("onClientResourceStart", resourceRoot, function()
    triggerServerEvent("nc:request", resourceRoot)
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
    clearCity()
    freeModels()
    for _, t in ipairs(S.timers) do if isTimer(t) then killTimer(t) end end
end)
